name: Project build workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 22.13.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.13.0
        cache: 'pnpm'  # Cache pnpm dependencies using pnpm-lock.yaml

    - name: Install pnpm
      run: npm install -g pnpm  # Install pnpm globally since it's not pre-installed

    - name: Install Dependencies
      run: pnpm install  # Use pnpm to install dependencies

    - name: Build
      run: pnpm run build --if-present  # Build using pnpm
